---
- name: Atualizacao de pacotes
  apt:
          name: '{{ item }}'
          #upgrade: dist # Atualiza todos os pacotes
          update_cache: yes
          state: latest
          cache_valid_time: 86400 # Um dia
  with_items:
          - tzdata
...
