---
- name: Teste CA
  hosts: teste
  remote_user: secimaadmin
  become: yes
  vars:
          ca_path_debian: /usr/local/share/ca-certificates
          ca_path_centos: /etc/pki/ca-trust/source/anchors
          ca_path:
            CentOS:
                    '{{ca_path_centos}}'
            Debian:
                    '{{ca_path_debian}}'
  tasks:

          - name: Copia certificado SEGPLANCAnew.crt
            copy:
                    src: '/etc/ansible/roles/base-config/files/SEGPLANCAnew.crt'
                    dest: '{{ca_path[ansible_distribution]}}'


          - name: Importa SEGPLANCAnew Debian
            shell: /usr/sbin/update-ca-certificates
            
            when:
               - ansible_distribution == "Debian"

          - name: Importa SEGPLANCAnew CentOS
            shell: /bin/update-ca-trust enable
            shell: /bin/update-ca-trust extract
            shell: /bin/update-ca-trust

            when:
               - ansible_distribution == "CentOS"

...
