---
- name: Teste CA
  hosts: teste
  remote_user: secimaadmin
  become: yes
  vars:
          ca_path_debian: /usr/local/share/ca-certificates
          ca_path_centos: /etc/pki/ca-trust/source/anchors
  tasks:
          - name: Cria diretorio
            file:
                    path: /usr/local/share/ca-certificates/extras
                    state: directory
             when:
               - ansible_distribution == "Debian"

          - name: Copia certificado SEGPLANCAnew.crt
            copy:
                    src: '/etc/ansible/roles/base-config/files/SEGPLANCAnew.crt'
                    dest: '/usr/local/share/ca-certificates/extras'

            when:
               - ansible_distribution == "Debian"

          - name: Atualiza certificados e importa SEGPLANCAnew
            shell: /usr/sbin/update-ca-certificates
            
            when:
               - ansible_distribution == "Debian"



...
