---
          - name: Adiciona repositorio buster-backports
            apt_repository:
                    repo: deb http://ftp.br.debian.org/debian/ buster-backports main contrib non-free
                    state: present
            when:
               - ansible_distribution == "Debian"
               - ansible_distribution_major_version == "10"

          - name: Atualiza distribuicao
            apt:
                    upgrade: yes       
            when:
                    - ansible_distribution == "Debian"

          - name: Instala open-vm-tools 11 do repositorio backports
            apt:
                    name: open-vm-tools
                    state: latest
                    default_release: buster-backports
                    update_cache: yes
            when:
                    - ansible_distribution == "Debian"

          - name: Instala open-vm-tools CentOS
            yum:
                    name: open-vm-tools
                    state: latest

          - name: Copia certificado SEGPLANCAnew.crt
            copy:
                    src: '/etc/ansible/roles/base-config/files/SEGPLANCAnew.crt'
                    dest: '{{ca_path[ansible_distribution]}}'

          - name: Importa SEGPLANCAnew Debian
            shell: /usr/sbin/update-ca-certificates
            when:
                    - ansible_distribution == "Debian"
                      
          - name: Importa SEGPLANCAnew CentOS
            shell: /bin/update-ca-trust enable
            shell: /bin/update-ca-trust extract
            shell: /bin/update-ca-trust
            when:
                    - ansible_distribution == "CentOS"

          - name: Instalacao do NTP, Vim, CA-Certificates
            package:
                    name:
                            - '{{ntp[ansible_distribution]}}'
                            - vim
                            - ca-certificates
                    state: present

          - name: Copia arquivos de configuracao
            copy:
                   src: '{{ item.src }}'
                   dest: '{{ item.dest }}'
            with_items:
                           - { src: '/etc/ansible/roles/base-config/files/ntp.conf', dest: '/etc/ntp.conf' }
                           - { src: '/etc/ansible/roles/base-config/files/vimrc', dest: '/etc/vim/vimrc' }
                           - { src: '/etc/ansible/roles/base-config/files/vimrc.local', dest: '/etc/vim/vimrc.local' }
                           - { src: '/etc/ansible/roles/base-config/files/bash.bashrc', dest: '/etc/bash.bashrc' }
            when:
                    - ansible_distribution == "Debian"

          - name: SELinux permissivo
            selinux:
                    policy: targeted
                    state: permissive
            when:
                    - ansible_distribution == "CentOS"
                      
          - name: Desabilita SELinux CentOS
            selinux:
                    state: disabled
            when:
                    - ansible_distribution == "CentOS"

          - name: Desabilita firewall CentOS
            service:
                    name: firewalld
                    state: stopped
                    enabled: false
            when:
                    - ansible_distribution == "CentOS"

          - name: Habilitar repositorio EPEL no CentOS
            dnf:
                    name: epel-release
                    state: latest
            when:
                    - ansible_distribution == "CentOS"

          - name: Configura chrony CentOS
            copy:
                    src: '/etc/ansible/roles/base-config/files/chrony.conf'
                    dest: '/etc'
                    owner: root
                    group: root
                    mode: 0644
            when:
                    - ansible_distribution == "CentOS"
            notify: ntp_centos

          - name: Habilita chronyd e open-vm-tools CentOS
            systemd:
                    name: chronyd
                    enabled: yes
            when:
                    - ansible_distribution == "CentOS"

          - name: Habilita vmtoolsd CentOS
            systemd:
                    name: vmtoolsd
                    enabled: yes
            when:
                    - ansible_distribution == "CentOS"

          - name: Flush handlers centos
            meta: flush_handlers

          - name: Atualiza todos os pacotes CentOS
            yum:
                    name: '*'
                    state: latest
            when:
                    - ansible_distribution == "CentOS"

          - name: Atualiza /etc/environment no Debian 10
            copy:
                    src: '/etc/ansible/roles/base-config/files/environment'
                    dest: '/etc'
                    owner: root
                    group: root
                    mode: 0644
            when:  
               - ansible_distribution == "Debian"
               - ansible_distribution_major_version == "10"
            notify: environment
...
